name: Deploy

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/homelab-ec2
          chmod 600 ~/.ssh/homelab-ec2

      - name: Fetch runner registration token
        id: get_token
        run: |
          TOKEN=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.RUNNER_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Skanderba8/homelab/actions/runners/registration-token \
            | jq -r '.token')
          echo "runner_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory.ini \
            --extra-vars "github_runner_token=${{ steps.get_token.outputs.runner_token }}"